
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Button btnOrdenar;
	
	private global::Gtk.Label lblOrdenar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnOrdenar = new global::Gtk.Button ();
		this.btnOrdenar.CanFocus = true;
		this.btnOrdenar.Name = "btnOrdenar";
		this.btnOrdenar.UseUnderline = true;
		this.btnOrdenar.Label = global::Mono.Unix.Catalog.GetString ("Ordenar");
		this.fixed1.Add (this.btnOrdenar);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnOrdenar]));
		w1.X = 88;
		w1.Y = 75;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblOrdenar = new global::Gtk.Label ();
		this.lblOrdenar.Name = "lblOrdenar";
		this.lblOrdenar.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.fixed1.Add (this.lblOrdenar);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblOrdenar]));
		w2.X = 267;
		w2.Y = 77;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnOrdenar.Clicked += new global::System.EventHandler (this.OnBtnOrdenarClicked);
	}
}
